
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile  # Aponta para o Dockerfile de desenvolvimento
    ports:
      - "3000:3000"  # Mapeia a porta 3000 do contêiner para a 3000 no host
    volumes:
      - .:/app  # Monta o diretório de trabalho no contêiner para permitir hot reload
      - /app/node_modules  # Evita sobrescrever node_modules do contêiner com o do host
    environment:
      - CHOKIDAR_USEPOLLING=true  # Necessário para detectar mudanças no código em alguns sistemas de arquivos